### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by fadeev**
* Replaced [deprecated](https://vuejs.org/v2/guide/components-slots.html#Deprecated-Syntax) `slot=` syntax with `v-slot:` throughout the app
* Replaced `.map` with `.forEach` where expression value is not handled.

### CODE REVIEW

**Comment by nylira** [comment]
Thanks! Making me look up map vs forEach right now. :)

**Comment by nylira** [comment]
Can I ask why you changed `template` to `div`? It feels like the output is cleaner if we just use `template`, to reduce surrounding divs.

**Comment by fadeev** [comment]
> Can I ask why you changed template to div? It feels like the output is cleaner if we just use template, to reduce surrounding divs.

You're right, that was not necessary to do. I tend not to use `template` outside of components accepting slots or some rare edge-cases, because it makes easier to differentiate between slots contents and just regular tags. I am more than happy to revert back to `template`.

Additional layers of divs almost never bother me, because performance implications are not significant unless you're dealing with large number of nodes.

However, I am mindful of top-level divs in components, because of how they affect scoped styling. Classes of top-level div fall under the scope of the parent's styling. Effectively, if you have a class on a top-level div it will be exposed to the parent and may be overwritten. Can be a great source of bugs 🐞

**Comment by nylira** [comment]
Thanks for the explanation. I'm in favor of this change

**Pull request merged**
