### PR TITLE
Wallet: fetch data in created hook

### PR DESCRIPTION
**Pull request by fadeev**
Wallet page depends on `settings`  and `blockchains`. Added both in created hook, so that eventually this logic can be removed from `App.vue`.

### CODE REVIEW

**Comment by fadeev** [comment]
I've removed all the data-fetching logic from `App.vue`. So far it seems that this did not break anything.

**Comment by nylira** [comment]
Some issues I've found after removal of the logic in app.vue:

The /accounts page doesn't tell the user which account they're currently following anymore:
image

Notifications page fails to load when clicking on it for the first time
image

The notifications page does load after coming back to it a second time

**Comment by nylira** [comment]
I fixed both of those bugs above, but I found one more. If you load the site from the accounts page and then navigate to notifications, the screen is empty

**Comment by fadeev** [comment]
@nylira should be fixed now.

**Pull request merged**
